import os
import sys
import asyncio
import platform # Added for cross-platform hostname
from anchorforge.config import Config
from anchorforge import blockchain_api
from anchorforge import key_manager # To generate new keys
from bsv import PrivateKey

# Workaround to enable relative imports if necessary
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

async def main():
    print("--- Initializing Environment for New Machine ---")
    
    # 1. Config triggers directory creation
    print(f"1. Directories checked: {Config.DATABASE_DIR}, {Config.CACHE_DIR}")

    # --- DECISION: Use existing keys or generate new ones? ---
    print("\n--- Wallet Configuration ---")
    if Config.UTXO_STORE_KEY_WIF:
        print(f"Key found in .env: {Config.UTXO_STORE_KEY_WIF[:10]}...")
        pk = PrivateKey(Config.UTXO_STORE_KEY_WIF)
        address = pk.address(network=Config.ACTIVE_NETWORK_BSV)
        print(f"Address: {address}")
        
        print("\nWARNING: If this key is used on other machines concurrently,")
        print("it may lead to 'Double Spend' errors.")
        print("For independent development, a unique key per machine is recommended.")
        
        # Optional prompt (commented out to allow non-interactive runs, but important note)
        # response = input("Do you want to keep this key? (y/n): ")
        # if response.lower() == 'n':
        #     # Logic to generate new keys and update .env could be added here
        #     pass

    else:
        print("No key found in .env. Generating new keys...")
        # Example call for Key-Gen (must be manually added to .env)
        try:
            # Use platform.node() for cross-platform compatibility (Windows/Linux/macOS)
            # This avoids the "os.uname" error on Windows
            hostname = platform.node()
            if not hostname:
                hostname = "dev_machine"
        except Exception:
            hostname = "dev_machine"

        new_key = key_manager.generate_key_pair(
            network_type=Config.ACTIVE_NETWORK_NAME,
            label=f"dev_machine_{hostname}",
            comment="Auto-generated by setup_env"
        )
        print("\nNEW KEY GENERATED:")
        print(f"WIF: {new_key['private_key_wif']}")
        print(f"Address: {new_key['public_address']}")
        print("--> Please add this WIF to your .env file now!")
        return # Abort so user can edit .env

    # 3. Load UTXOs from Blockchain (Full Repair)
    # We call the manager as a subprocess to simulate CLI arguments easily
    print("\n3. Loading UTXOs from Blockchain (Full Repair)...")
    cmd = f"python utxo_manager.py --address {address} --network {Config.ACTIVE_NETWORK_NAME} full-repair"
    os.system(cmd)

    # 4. Header Sync
    print("\n4. Synchronizing Block Headers...")
    cmd_sync = f"python af_sync.py --last 2000 --network {Config.ACTIVE_NETWORK_NAME}"
    os.system(cmd_sync)

    print("\n--- Setup complete. You can now start developing. ---")

if __name__ == "__main__":
    asyncio.run(main())