import os
import sys
import asyncio
import platform # Added for cross-platform hostname
from anchorforge.config import Config
from anchorforge import blockchain_api
from anchorforge import key_manager # To generate new keys
from bsv import PrivateKey

# Workaround to enable relative imports if necessary
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

async def main():
    print("--- Initializing Environment for New Machine ---")
    
    # 1. Config triggers directory creation
    # Check for new V2.1 structure attributes, fallback if Config isn't updated yet
    db_dir = getattr(Config, 'DATABASE_DIR', 'database')
    wallet_dir = getattr(Config, 'WALLET_CACHE_DIR', getattr(Config, 'CACHE_DIR', 'cache'))
    public_dir = getattr(Config, 'PUBLIC_CACHE_DIR', 'cache/public')

    print(f"1. Directories checked:")
    print(f"   - Database: {db_dir}")
    print(f"   - Wallet Cache: {wallet_dir}")
    print(f"   - Public Cache: {public_dir}")

    # --- DECISION: Use existing keys or generate new ones? ---
    print("\n--- Wallet Configuration ---")
    if Config.UTXO_STORE_KEY_WIF:
        print(f"Key found in .env: {Config.UTXO_STORE_KEY_WIF[:10]}...")
        pk = PrivateKey(Config.UTXO_STORE_KEY_WIF)
        address = pk.address(network=Config.ACTIVE_NETWORK_BSV)
        print(f"Address: {address}")
        
        print("\nWARNING: If this key is used on other machines concurrently,")
        print("it may lead to 'Double Spend' errors.")
        print("For independent development, a unique key per machine is recommended.")
        
        # Optional prompt
        # response = input("Do you want to keep this key? (y/n): ")

    else:
        print("No key found in .env. Generating new keys...")
        try:
            hostname = platform.node()
            if not hostname: hostname = "dev_machine"
        except Exception:
            hostname = "dev_machine"

        new_key = key_manager.generate_key_pair(
            network_type=Config.ACTIVE_NETWORK_NAME,
            label=f"dev_machine_{hostname}",
            comment="Auto-generated by setup_env"
        )
        print("\nNEW KEY GENERATED:")
        print(f"WIF: {new_key['private_key_wif']}")
        print(f"Address: {new_key['public_address']}")
        print("--> Please add this WIF to your .env file now!")
        return # Abort so user can edit .env

    # 3. Load UTXOs from Blockchain (Full Repair)
    # Uses the new af_utxo_manager.py tool (assumed to be in root)
    print("\n3. Loading UTXOs from Blockchain (Full Repair)...")
    
    # Check if we should use the new CLI tool name or fallback to library path
    manager_script = "af_utxo_manager.py"
    if not os.path.exists(manager_script):
        # Fallback to internal path if CLI wrapper missing
        manager_script = os.path.join("anchorforge", "utxo_manager.py")
        
    if os.path.exists(manager_script):
        cmd = f"python {manager_script} --address {address} --network {Config.ACTIVE_NETWORK_NAME} full-repair"
        print(f"Executing: {cmd}")
        os.system(cmd)
    else:
        print(f"⚠️ Warning: UTXO Manager script not found at {manager_script}. Skipping initial sync.")

    # 4. Header Sync
    print("\n4. Synchronizing Block Headers...")
    cmd_sync = f"python af_sync.py --last 2000 --network {Config.ACTIVE_NETWORK_NAME}"
    os.system(cmd_sync)

    print("\n--- Setup complete. You can now start developing. ---")

if __name__ == "__main__":
    asyncio.run(main())